config/routes.rb
Rails.application.routes.draw do
  devise_for :users
root 'posts#index', as: 'home'

# get 'about' => 'pages#about', as: 'about'
get 'ingredients' => 'ingredients#index', as:'ingredients'
resources :posts, :ingredients, :items, :creators, :myclients, :myorders, :deliveries
  end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :title, presence: true, length: {minimum: 8}
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @ingredient = Ingredient.all
  end

  def new
    @ingredient = Ingredient.new
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def update
    @ingredient = Ingredient.find(params[:id])
    if(@ingredient.update(ingredient_params))                  #save in the table when validated
    redirect_to @ingredient
    else
    render 'edit' #if title not validated
  end
  end

  def destroy
  @ingredient = Ingredient.find(params[:id])
  @ingredient.destroy
  redirect_to ingredients_path
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    # @ingredient.save
    # redirect_to @ingredient

    respond_to do |format|
       if @ingredient.save
         format.html { redirect_to @ingredient, notice: 'Success'}
       else
         format.html { render :new}
    end
  end

end

  private def ingredient_params
    params.require(:ingredient).permit(:name, :price, :production_date, :storage_time, :creator ) #take allowed data
  end

  end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/edit.html.erb
<h2>Edit the ingredient</h2>
<%= form_for :ingredient, url: ingredient_path(@ingredient), method: :patch do |f| %>
<% if @ingredient.errors.any? %>
<%@ingredient.errors.full_messages.each do |msg| %>
<div class="alert alert-danger"><%= msg %></div>
<% end %>
<% end %>
<p>
  Title<br>
  <%= f.text_field(:title, {:class => 'form-control'}) %>
</p>

<p>
  Producted on<br>
  <%= f.date_field(:production_date, {:class => 'form-control'}) %>
</p>
<p>
  Time u can store it<br>
  <%= f.text_field(:storage_time, {:class => 'form-control'}) %>
</p>
<p>
  <%= f.submit({:class => 'btn btn-success'}) %>
</p>
<p>
  <%= f.submit({:class => 'btn btn-success'}) %>
</p>
<% end %>

app/views/ingredients/index.html.erb
<h1> All our ingredients </h1>
<% @ingredient.each do |ingredient| %>
  <div class="alert alert-light">
    <h3><%= ingredient.title %></h3>
    <%= link_to "Read more", ingredient_path(ingredient), :class=>'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/ingredients/new.html.erb
<h2>Add new ingredient</h2>
<%= form_for :ingredient, url: ingredients_path do |f| %>
  <% if @ingredient.errors.any? %>
  <%@ingredient.errors.full_messages.each do |msg| %>
  <div class="alert alert-danger"><%= msg %></div>
  <% end %>
  <% end %>
<p>
  Title<br>
  <%= f.text_field(:title, {:class => 'form-control'}) %>
</p>
<p>
  Produced on<br>
  <%= f.date_field(:production_date, {:class => 'form-control'}) %>
</p>
<p>
  Time u can store it<br>
  <%= f.text_field(:storage_time, {:class => 'form-control'}) %>
</p>
<p>
  <%= f.submit({:class => 'btn btn-success'}) %>
</p>
<% end %>

app/views/ingredients/show.html.erb
<h1> <%= @ingredient.title %></h1>
<p> <%= @ingredient.production_date %></p>
<p> <%= @ingredient.storage_time %></p>
<hr>
<%= link_to "Edit", edit_ingredient_path(@ingredient), :class => 'btn btn-warning' %>
<%= link_to "Delete", ingredient_path(@ingredient), method: :delete, data:{confirm: "R u sure u wanna delete it?"}, :class => 'btn btn-danger' %>