config/routes.rb
Rails.application.routes.draw do
  devise_for :users
root 'posts#index', as: 'home'

# get 'about' => 'pages#about', as: 'about'
get 'ingredients' => 'ingredients#index', as:'ingredients'
resources :posts, :ingredients, :items, :creators, :myclients, :myorders, :deliveries
  end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :myorder
  validates :price, :presence => {:message => "Вкажіть ціну доставки"}
end

app/controllers/deliveries_controller.rb
class DeliveriesController < ApplicationController
before_action :authenticate_user!, except: [:index, :show]
      def show
        @delivery = Deliveries.find(params[:id])
      end

      def destroy
        @delivery = Delivery.find(params[:id])

        @delivery.destroy

        redirect_to Delivery
      end

      def new
        @delivery = Delivery.new
      end

      def edit
        @delivery = Delivery.find(params[:id])
      end

      def update
        @delivery = Delivery.find(params[:id])
        if(@delivery.update(delivery_params))                  #save in the table when validated
        redirect_to Delivery
        else
        render 'edit' #if title not validated
      end
      end


        def create
          @delivery = Delivery.new(delivery_params)

          respond_to do |format|
             if @delivery.save
               format.html { redirect_to Delivery, notice: 'Success'}
             else
               format.html { render :new}
          end
        end

      end

      private def delivery_params
        params.require(:delivery).permit(:myorder_id, :price) #take allowed data
      end
end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

app/views/deliveries/edit.html.erb
<h2>Редагувати інформацію про доставку</h2>
<%= form_for :delivery, url: delivery_path(@delivery), method: :patch do |f| %>
<% if @delivery.errors.any? %>
<%@delivery.errors.full_messages.each do |msg| %>
<div class="alert alert-danger"><%= msg %></div>
<% end %>
<% end %>

<p>
  Код замовлення<br>
   <%= f.collection_select :myorder_id, Myorder.order(:id), :id, :id, {:style => "height:35px;", :class => 'form-control'} %>
</p>


<p>
  Ціна доставки<br>
    <%= f.number_field(:price, {:style => "height:35px;", :class => 'form-control'}) %>
</p>

<p>
  <%= f.submit({:style => "height:35px;", :class => 'btn btn-success'}) %>
</p>
<% end %>

app/views/deliveries/index.html.erb
<a><%= link_to "Додати запис", new_delivery_path,:style=>'font-size:large; border-radius:5px;', :class =>'col-lg-12 btn btn-success btn-lg'%></th>
</a>
<br><br><br>
<table class="table table-hover table-bordered text-center">
<tr class="thead-light">
  <th style="text-align:center;">Код замовлення</th>
  <th style="text-align:center;">Місто замовника</th>
  <th style="text-align:center;">Місто відправника</th>
  <th style="text-align:center;">Ціна доставки</th>
  <th style="text-align:center;">Ціна замовлення</th>
  <th style="text-align:center;">До сплати загалом</th>
<th></th>
<th></th>
</tr>
<% Delivery.all.each do |delivery| %>
<tr>
<td><%= delivery.myorder_id%></td>
<td><%= delivery.myorder.myclient.city%></td>
<td><%= delivery.myorder.item.creator.city %></td>
<td><%= delivery.price %> </td>
<td><%= delivery.myorder.item.price %> </td>
<td><%= delivery.myorder.item.price.to_f+delivery.price.to_f %> </td>
<td><%= link_to '<i class="icon-edit"></i>'.html_safe, edit_delivery_path(delivery.id), :class =>'btn btn-outline-warning btn-sm'%></td>
<td>  <%= link_to '<i class="icon-trash"></i>'.html_safe, delivery_path(delivery.id), method: :delete, data:{confirm: "Видалити запис?"}, :class =>'btn btn-outline-danger btn-sm'%></td>
</tr>
<% end %>
</table>

app/views/deliveries/new.html.erb
<h2>Додати інформацію про доставку</h2>
<%= form_for :delivery, url: deliveries_path do |f| %>
  <% if @delivery.errors.any? %>
  <%@delivery.errors.full_messages.each do |msg| %>
  <div class="alert alert-danger"><%= msg %></div>
  <% end %>
  <% end %>
  <p>
    Код замовлення<br>
     <%= f.collection_select :myorder_id, Myorder.order(:id), :id, :id, {:style => "height:35px;", :class => 'form-control'} %>
  </p>
  <p>
    Ціна доставки<br>
      <%= f.number_field(:price, {:style => "height:35px;", :class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit({:style => "height:35px;", :class => 'btn btn-success'}) %>
  </p>
  <% end %>