config/routes.rb
Rails.application.routes.draw do
  devise_for :users
root 'posts#index', as: 'home'

# get 'about' => 'pages#about', as: 'about'
get 'ingredients' => 'ingredients#index', as:'ingredients'
resources :posts, :ingredients, :items, :creators, :myclients, :myorders, :deliveries
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/creator.rb
class Creator < ApplicationRecord
  validates :name, :presence => {:message => "Заповніть назву виробника"}
  validates :registration_date, :presence => {:message => "Вкажіть дату реєстрації"}
  validates :city,  :presence => {:message => "Вкажіть місто виробника"}
  validates :specialization, :presence => {:message => "Для якої галузі створюються твори мистецтва цим виробником?"}
  validates :phone_number, :presence => {:message => "Заповніть номер телефону"}
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :myorder
  validates :price, :presence => {:message => "Вкажіть ціну доставки"}
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :title, presence: true, length: {minimum: 8}
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :creator
    validates :name, :presence => {:message => "Вкажіть назву творіння"}
    validates :price,  numericality: {greater_than: 0, :message => "Розкрийте вартість цього шедевру, ціна має бути більша за 0"}
    validates :production_date, :presence => {:message => "Коли було створене це диво?"}
    validates :storage_time, numericality: {greater_than: 0, :message => "Скільки місяців служитиме цей витвір?"}
end

app/models/myclient.rb
class Myclient < ApplicationRecord
  validates :name, :presence => {:message => "Вкажіть ім'я клієнта"}
  validates :birth,  :presence => {:message => "Заповніть дату народження"}
  validates :company, :presence => {:message => "У якій компанії працює Ваш замовник?"}
  validates :phone_number, :presence => {:message => "Вкажіть номер телефону"}
  validates :city, :presence => {:message => "Із якого міста замовник?"}
end

app/models/myorder.rb
class Myorder < ApplicationRecord
  belongs_to :myclient
  belongs_to :item

  validates :order_date,  :presence => {:message => "Заповніть дату замовлення"}
  validates :amount, numericality: {greater_than: 0, :message => "Скільки одиниць товару замовлено? (не менше однієї)"}

end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: {minimum: 8}
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
end

app/controllers/creators_controller.rb
class CreatorsController < ApplicationController
before_action :authenticate_user!, except: [:index, :show]
  def show
    @creator = Creators.find(params[:id])
  end

  def destroy
    @creator = Creator.find(params[:id])

    @creator.destroy

    redirect_to Creator
  end

  def new
    @creator = Creator.new
  end

  def edit
    @creator = Creator.find(params[:id])
  end

  def update
    @creator = Creator.find(params[:id])
    if(@creator.update(creator_params))                  #save in the table when validated
    redirect_to Creator
    else
    render 'edit' #if title not validated
  end
  end


    def create
      @creator = Creator.new(creator_params)

      respond_to do |format|
         if @creator.save
           format.html { redirect_to Creator, notice: 'Success'}
         else
           format.html { render :new}
      end
    end

  end

  private def creator_params
    params.require(:creator).permit(:name, :registration_date, :city, :specialization, :phone_number ) #take allowed data
  end

  end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
before_action :authenticate_user!, except: [:index, :show]
  def show
    @item = Items.find(params[:id])
  end

  def destroy
    @item = Item.find(params[:id])

    @item.destroy

    redirect_to Item
  end

  def new
    @item = Item.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if(@item.update(item_params))                  #save in the table when validated
    redirect_to Item
    else
    render 'edit' #if title not validated
  end
  end


    def create
      @item = Item.new(item_params)

      respond_to do |format|
         if @item.save
           format.html { redirect_to Item, notice: 'Success'}
         else
           format.html { render :new}
      end
    end

  end

  private def item_params
    params.require(:item).permit(:name, :price, :production_date, :storage_time, :creator_id ) #take allowed data
  end

end

app/controllers/myclients_controller.rb
class MyclientsController < ApplicationController
before_action :authenticate_user!, except: [:index, :show]
    def show
      @myclient = Myclients.find(params[:id])
    end

    def destroy
      @myclient = Myclient.find(params[:id])

      @myclient.destroy

      redirect_to Myclient
    end

    def new
      @myclient = Myclient.new
    end

    def edit
      @myclient = Myclient.find(params[:id])
    end

    def update
      @myclient = Myclient.find(params[:id])
      if(@myclient.update(myclient_params))                  #save in the table when validated
      redirect_to Myclient
      else
      render 'edit' #if title not validated
    end
    end


      def create
        @myclient = Myclient.new(myclient_params)

        respond_to do |format|
           if @myclient.save
             format.html { redirect_to Myclient, notice: 'Success'}
           else
             format.html { render :new}
        end
      end

    end

    private def myclient_params
      params.require(:myclient).permit(:name, :birth, :company, :phone_number, :city ) #take allowed data
    end
end

app/controllers/myorders_controller.rb
class MyordersController < ApplicationController
before_action :authenticate_user!, except: [:index, :show]
    def show
      @myorder = Myorders.find(params[:id])
    end

    def destroy
      @myorder = Myorder.find(params[:id])

      @myorder.destroy

      redirect_to Myorder
    end

    def new
      @myorder = Myorder.new
    end

    def edit
      @myorder = Myorder.find(params[:id])
    end

    def update
      @myorder = Myorder.find(params[:id])
      if(@myorder.update(myorder_params))                  #save in the table when validated
      redirect_to Myorder
      else
      render 'edit' #if title not validated
    end
    end


      def create
        @myorder = Myorder.new(myorder_params)

        respond_to do |format|
           if @myorder.save
             format.html { redirect_to Myorder, notice: 'Success'}
           else
             format.html { render :new}
        end
      end

    end

    private def myorder_params
      params.require(:myorder).permit(:item_id, :order_date, :amount, :myclient_id) #take allowed data
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
   @heading = "About"
   @text = "some text"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
# http_basic_authenticate_with name: "admin", password: "1",
# except: [:index, :show]
before_action :authenticate_user!, except: [:index, :show]

  def index
    @post = Post.all
  end

  def new
    # @post = Post.new
    @post = current_user.posts.build
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if(@post.update(post_params))                  #save in the table when validated
    redirect_to @post
    else
    render 'edit' #if title not validated
  end
  end

def destroy
  @post = Post.find(params[:id])
  @post.destroy
  redirect_to posts_path
end

  def create

    @post = current_user.posts.build(post_params) #write to the create_table

  respond_to do |format|
     if @post.save
       format.html { redirect_to @post, notice: 'Success'}
     else
       format.html { render :new}
  end
end
end

  private def post_params
    params.require(:post).permit(:title, :body, :price) #take allowed data
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creators_helper.rb
module CreatorsHelper
end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/myclient_helper.rb
module MyclientHelper
end

app/helpers/myorder_helper.rb
module MyorderHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/creators/edit.html.erb
<h2>Редагування інформації про виробника</h2>
<%= form_for :creator, url: creator_path(@creator), method: :patch do |f| %>
<% if @creator.errors.any? %>
<%@creator.errors.full_messages.each do |msg| %>
<div class="alert alert-danger"><%= msg %></div>
<% end %>
<% end %>
<p>
  Назва<br>
  <%= f.text_field(:name, {:style =>"height:35px;", :class => 'form-control'}) %>
</p>
<p>
  Дата реєстрації<br>
  <%= f.date_field(:registration_date, {:style =>"height:35px;", :class => 'form-control'}) %>
</p>
<p>
  Місто<br>
  <%= f.text_field(:city, {:style =>"height:35px;", :class => 'form-control'}) %>
</p>
<p>
  Спеціалізація<br>
  <%= f.text_field(:specialization, {:style =>"height:35px;", :class => 'form-control'}) %>
</p>
<p>
  Телефон<br>
<%= f.text_field(:phone_number, {:style =>"height:35px;", :class => 'form-control'}) %>
</p>

<p>
  <%= f.submit({:style =>"height:35px;", :class => 'btn btn-success'}) %>
</p>
<% end %>

app/views/creators/index.html.erb
<%= link_to "Додати запис", new_creator_path, :style=>"font-size:large; border-radius:5px;", :class =>'btn btn-success col-lg-12'%>

<div class="card-group" style="display:inline-flex;">
  <% Creator.all.each do |creator| %>
<div class="col-sm-4">
  <div class="card bg-light mb-3" style="border-radius:5px; font-size:12px; margin:20px;">
    <div class="card-body">
      <span class="fa fa-user"></span>
      <h5 class="card-title " style="text-shadow: 1px 1px 5px darkgrey; text-align:center; font-size:large; border-bottom: 1px solid lightgrey;"><i class="icon-ok" style="margin-right:5px;"> </i><%= creator.name %></h5>
       <i class="icon-calendar" style="margin-right:5px;"> </i><strong>Дата реєстрації:</strong>   <%= creator.registration_date.strftime("%m/%d/%Y") %> <br>
      <i class="icon-screenshot" style="margin-right:5px;"> </i> <strong>Місто:</strong> <%= creator.city %> <br>
    <i class="icon-briefcase" style="margin-right:5px;"> </i>  <strong>Спеціалізація:</strong>   <%= creator.specialization %> міс. <br>
      <i class="icon-phone" style="margin-right:5px;"> </i><strong>Телефон:</strong> <%= creator.phone_number %>
      <br><br>
      <%= link_to '<i class="icon-edit"></i>'.html_safe, edit_creator_path(creator.id), :class =>'btn btn-warning col-lg-2 offset-4'%>
        <%= link_to '<i class="icon-trash"></i>'.html_safe, creator_path(creator.id), method: :delete, data:{confirm: "Справді бажаєте видалити цей товар?"}, :class =>'btn btn-danger col-lg-2'%>
    </div>
  </div>
</div>
<% end %>
</div>

app/views/creators/new.html.erb
<h2>Створення нового виробника</h2>
<%= form_for :creator, url: creators_path do |f| %>
  <% if @creator.errors.any? %>
  <%@creator.errors.full_messages.each do |msg| %>
  <div class="alert alert-danger"><%= msg %></div>
  <% end %>
  <% end %>
<p>
  Назва<br>
  <%= f.text_field(:name, {:style =>"height:35px;", :class => 'form-control'}) %>
</p>
<p>
  Дата реєстрації<br>
  <%= f.date_field(:registration_date, {:style =>"height:35px;", :class => 'form-control'}) %>
</p>
<p>
  Місто<br>
  <%= f.text_field(:city, {:style =>"height:35px;", :class => 'form-control'}) %>
</p>
<p>
  Спеціалізація<br>
  <%= f.text_field(:specialization, {:style =>"height:35px;", :class => 'form-control'}) %>
</p>
<p>
  Телефон<br>
<%= f.text_field(:phone_number, {:style =>"height:35px;", :class => 'form-control'}) %>
</p>

<p>
  <%= f.submit({:style =>"height:35px;", :class => 'btn btn-success'}) %>
</p>
<% end %>

app/views/items/edit.html.erb
<h2>Редагувати товар</h2>
<%= form_for :item, url: item_path(@item), method: :patch do |f| %>
<% if @item.errors.any? %>
<%@item.errors.full_messages.each do |msg| %>
<div class="alert alert-danger"><%= msg %></div>
<% end %>
<% end %>
<p>
  Назва<br>
  <%= f.text_field(:name, {:style =>"height:35px;", :class => 'form-control'}) %>
</p>
<p>
  Ціна<br>
  <%= f.number_field(:price, {:style =>"height:35px;", :class => 'form-control'}) %>
</p>
<p>
  Дата виробництва<br>
  <%= f.date_field(:production_date, {:style =>"height:35px;", :class => 'form-control'}) %>
</p>
<p>
  Термін зберігання<br>
  <%= f.number_field(:storage_time, {:style =>"height:35px;", :class => 'form-control'}) %>
</p>
<p>
  Виробник<br>
   <%= f.collection_select :creator_id, Creator.order(:name), :id, :name, {:style =>"height:35px;", :class => 'form-control'} %>
</p>

<p>
  <%= f.submit({:style =>"height:35px;", :class => 'btn btn-success'}) %>
</p>
<% end %>

app/views/items/index.html.erb
<%= link_to "Додати запис", new_item_path, :style=>"font-size:large; border-radius:5px;", :class =>'btn btn-success col-lg-12'%>

<div class="card-group" style="display:inline-flex;">
  <% Item.all.each do |item| %>
<div class="col-sm-4">
  <div class="card bg-light mb-3" style="border-radius:5px; font-size:12px; margin:20px;">
    <div class="card-body">
      <span class="fa fa-user"></span>
      <h5 class="card-title " style="text-shadow: 1px 1px 5px darkgrey; text-align:center; font-size:large; border-bottom: 1px solid lightgrey;"><i class="icon-ok" style="margin-right:5px;"> </i><%= item.name %></h5>
      <i class="icon-euro" style="margin-right:5px;"> </i> <strong>Вартість:</strong> <%= item.price %> <br>
       <i class="icon-calendar" style="margin-right:5px;"> </i><strong>Дата створення:</strong>   <%= item.production_date.strftime("%m/%d/%Y") %> <br>
    <i class="icon-calendar" style="margin-right:5px;"> </i>  <strong>Термін зберігання:</strong>   <%= item.storage_time %> міс. <br>
      <i class="icon-briefcase" style="margin-right:5px;"> </i><strong>Виробник:</strong> <%= item.creator.try(:name) %>
      <br><br>
      <%= link_to '<i class="icon-edit"></i>'.html_safe, edit_item_path(item.id), :class =>'btn btn-warning col-lg-2 offset-4'%>
        <%= link_to '<i class="icon-trash"></i>'.html_safe, item_path(item.id), method: :delete, data:{confirm: "Справді бажаєте видалити цей товар?"}, :class =>'btn btn-danger col-lg-2'%>
    </div>
  </div>
</div>
<% end %>
</div>

app/views/items/new.html.erb
<h2>Додати новий товар</h2>
<%= form_for :item, url: items_path do |f| %>
  <% if @item.errors.any? %>
  <%@item.errors.full_messages.each do |msg| %>
  <div class="alert alert-danger"><%= msg %></div>
  <% end %>
  <% end %>
<p>
  Назва<br>
  <%= f.text_field(:name, {:style =>"height:35px;", :class => 'form-control'}) %>
</p>
<p>
  Ціна<br>
  <%= f.number_field(:price, {:style =>"height:35px;",:class => 'form-control'}) %>
</p>
<p>
  Дата виробництва<br>
  <%= f.date_field(:production_date, {:style =>"height:35px;",:class => 'form-control'}) %>
</p>
<p>
  Термін зберігання<br>
  <%= f.number_field(:storage_time, {:style =>"height:35px;",:class => 'form-control'}) %>
</p>
<p>
  Виробник<br>
   <%= f.collection_select :creator_id, Creator.order(:name), :id, :name, {:style =>"height:35px;", :class => 'form-control'} %>
</p>

<p>
  <%= f.submit({:style =>"height:35px;", :class => 'btn btn-success'}) %>
</p>
<% end %>

app/views/myclients/edit.html.erb
<h2>Редагувати інформацію про замовника</h2>
<%= form_for :myclient, url: myclient_path(@myclient), method: :patch do |f| %>
<% if @myclient.errors.any? %>
<%@myclient.errors.full_messages.each do |msg| %>
<div class="alert alert-danger"><%= msg %></div>
<% end %>
<% end %>

<p>
  Ім'я замовника<br>
  <%= f.text_field(:name, {:style => "height:35px;", :class => 'form-control'}) %>
</p>
<p>
  Дата народження<br>
  <%= f.date_field(:birth, {:style => "height:35px;", :class => 'form-control'}) %>
</p>
<p>
  Місце роботи<br>
  <%= f.text_field(:company, {:style => "height:35px;", :class => 'form-control'}) %>
</p>
<p>
  Номер телефону<br>
  <%= f.text_field(:phone_number, {:style => "height:35px;", :class => 'form-control'}) %>
</p>
<p>
  Місто<br>
  <%= f.text_field(:city, {:style => "height:35px;", :class => 'form-control'}) %>
</p>
<p>
  <%= f.submit({:style => "height:35px;", :class => 'btn btn-success'}) %>
</p>
<% end %>

app/views/myclients/index.html.erb
<%= link_to "Додати запис", new_myclient_path, :style=>"font-size:large; border-radius:5px;", :class =>'btn btn-success col-lg-12'%>

<div class="card-group" style="display:inline-flex;">
  <% Myclient.all.each do |myclient| %>
<div class="col-sm-4">
  <div class="card bg-light mb-3" style="border-radius:5px; font-size:12px; margin:20px;">
    <div class="card-body">
      <span class="fa fa-user"></span>
      <h5 class="card-title " style="text-shadow: 1px 1px 5px darkgrey; text-align:center; font-size:large; border-bottom: 1px solid lightgrey;"><i class="icon-ok" style="margin-right:5px;"> </i><%= myclient.name %></h5>
      <i class="icon-calendar" style="margin-right:5px;"> </i><strong>Дата народження:</strong>   <%= myclient.birth.strftime("%m/%d/%Y") %> <br>
      <i class="icon-briefcase" style="margin-right:5px;"> </i><strong>Місце роботи:</strong> <%= myclient.company %><br>
      <i class="icon-phone" style="margin-right:5px;"> </i> <strong>Номер телефону:</strong> <%= myclient.phone_number %> <br>
      <i class="icon-screenshot" style="margin-right:5px;"> </i>  <strong>Місто:</strong>   <%= myclient.city %> <br>
          <br><br>
      <%= link_to '<i class="icon-edit"></i>'.html_safe, edit_myclient_path(myclient.id), :class =>'btn btn-warning col-lg-2 offset-4'%>
        <%= link_to '<i class="icon-trash"></i>'.html_safe, myclient_path(myclient.id), method: :delete, data:{confirm: "Справді бажаєте видалити цей товар?"}, :class =>'btn btn-danger col-lg-2'%>
    </div>
  </div>
</div>
<% end %>
</div>
<!-- <table border="1">
<tr>
  <th>Ім'я замовника</th>
  <th>Дата народження</th>
  <th>Місце роботи</th>
  <th>Номер телефону</th>
  <th>Місто</th>

<th><%= link_to "Додати запис", new_myclient_path, :class =>'btn btn-success btn-sm'%></th>
</tr>
<% Myclient.all.each do |myclient| %>
<tr>
<td><%= myclient.name %></td>
<td><%= myclient.birth.strftime("%m/%d/%Y") %></td>
<td><%= myclient.company %></td>
<td><%= myclient.phone_number %> </td>
<td><%= myclient.city %> </td>

<td><%= link_to "Редагувати", edit_myclient_path(myclient.id), :class =>'btn btn-warning btn-sm'%>
  <%= link_to "Видалити", myclient_path(myclient.id), method: :delete, data:{confirm: "Видалити запис?"}, :class =>'btn btn-danger btn-sm'%></td>
</tr>
<% end %>
</table> -->

app/views/myclients/new.html.erb
<h2>Створити нового замовника</h2>
<%= form_for :myclient, url: myclients_path do |f| %>
  <% if @myclient.errors.any? %>
  <%@myclient.errors.full_messages.each do |msg| %>
  <div class="alert alert-danger"><%= msg %></div>
  <% end %>
  <% end %>
  <p>
    Ім'я замовника<br>
    <%= f.text_field(:name, {:style => "height:35px;", :class => 'form-control'}) %>
  </p>
  <p>
    Дата народження<br>
    <%= f.date_field(:birth, {:style => "height:35px;", :class => 'form-control'}) %>
  </p>
  <p>
    Місце роботи<br>
    <%= f.text_field(:company, {:style => "height:35px;", :class => 'form-control'}) %>
  </p>
  <p>
    Номер телефону<br>
    <%= f.text_field(:phone_number, {:style => "height:35px;", :class => 'form-control'}) %>
  </p>
  <p>
    Місто<br>
    <%= f.text_field(:city, {:style => "height:35px;", :class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit({:style => "height:35px;", :class => 'btn btn-success'}) %>
  </p>
  <% end %>

app/views/myorders/edit.html.erb
<h2>Редагування інформації про замовлення</h2>
<%= form_for :myorder, url: myorder_path(@myorder), method: :patch do |f| %>
<% if @myorder.errors.any? %>
<%@myorder.errors.full_messages.each do |msg| %>
<div class="alert alert-danger"><%= msg %></div>
<% end %>
<% end %>

<p>
  Назва товару<br>
   <%= f.collection_select :item_id, Item.order(:name), :id, :name, {:class => 'form-control'} %>
</p>
<p>
  Дата замовлення<br>
  <%= f.date_field(:order_date, {:style => "height:35px;", :class => 'form-control'}) %>
</p>
<p>
  Кількість одиниць<br>
  <%= f.number_field(:amount, {:style => "height:35px;", :class => 'form-control'}) %>
</p>
<p>
  Замовник<br>
   <%= f.collection_select :myclient_id, Myclient.order(:name), :id, :name, {:style => "height:35px;", :class => 'form-control'} %>
</p>

<p>
  <%= f.submit({:style => "height:35px;", :class => 'btn btn-success'}) %>
</p>
<% end %>

app/views/myorders/index.html.erb
<a><%= link_to "Додати запис", new_myorder_path, :style=>'font-size:large; border-radius:5px;',:class =>'col-lg-12 btn btn-success btn-sm'%></th>
</a>
<br><br><br>
<table class="table table-hover table-bordered text-center">
<tr class="thead-light">
  <th style="text-align:center;">Назва товару</th>
  <th style="text-align:center;">Дата замовлення</th>
  <th style="text-align:center;">Кількість одиниць</th>
  <th style="text-align:center;">Замовник</th>
  <th style="text-align:center;">Виробник</th>
  <th style="text-align:center;">Вартість замовлення</th>
<th></th>
<th></th>
</tr>
<% Myorder.all.each do |myorder| %>
<tr>
<td><%= myorder.item.try(:name)%></td>
<td><%= myorder.order_date.strftime("%m/%d/%Y")%></td>
<td><%= myorder.amount %></td>
<td><%= myorder.myclient.try(:name) %> </td>
<td><%= myorder.item.creator.try(:name) %> </td>
<td><%= (myorder.amount.to_f*myorder.item.price.to_f).round(2) %></td>
<td><%= link_to '<i class="icon-edit"></i>'.html_safe, edit_myorder_path(myorder.id), :class =>'btn btn-outline-warning btn-sm'%></td>
<td>  <%= link_to '<i class="icon-trash"></i>'.html_safe, myorder_path(myorder.id), method: :delete, data:{confirm: "Видалити запис?"}, :class =>'btn btn-outline-danger btn-sm'%></td>
</tr>
<% end %>
</table>

app/views/myorders/new.html.erb
<h2>Додати нове замовлення</h2>
<%= form_for :myorder, url: myorders_path do |f| %>
  <% if @myorder.errors.any? %>
  <%@myorder.errors.full_messages.each do |msg| %>
  <div class="alert alert-danger"><%= msg %></div>
  <% end %>
  <% end %>
  <p>
    Назва товару<br>
     <%= f.collection_select :item_id, Item.order(:name), :id, :name, {:class => 'form-control'} %>
  </p>
  <p>
    Дата замовлення<br>
    <%= f.date_field(:order_date, {:style => "height:35px;", :class => 'form-control'}) %>
  </p>
  <p>
    Кількість одиниць<br>
    <%= f.number_field(:amount, {:style => "height:35px;", :class => 'form-control'}) %>
  </p>
  <p>
    Замовник<br>
     <%= f.collection_select :myclient_id, Myclient.order(:name), :id, :name, {:style => "height:35px;", :class => 'form-control'} %>
  </p>

  <p>
    <%= f.submit({:style => "height:35px;", :class => 'btn btn-success'}) %>
  </p>
  <% end %>

app/views/posts/edit.html.erb
<h2>Edit the post</h2>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
<% if @post.errors.any? %>
<%@post.errors.full_messages.each do |msg| %>
<div class="alert alert-danger"><%= msg %></div>
<% end %>
<% end %>
<p>
  Title<br>
  <%= f.text_field(:title, {:class => 'form-control'}) %>
</p>
<p>
  Body<br>
  <%= f.text_area(:body, {:class => 'form-control'}) %>
</p>
<p>
  Price<br>
  <%= f.text_field(:price, {:class => 'form-control'}) %>
</p>
<p>
  <%= f.submit({:class => 'btn btn-success'}) %>
</p>
<% end %>

app/views/posts/new.html.erb
<h2>Add new post</h2>

<%= form_for :post, url: posts_path do |f| %>
<% if @post.errors.any? %>
<%@post.errors.full_messages.each do |msg| %>
<div class="alert alert-danger"><%= msg %></div>
<% end %>
<% end %>
<p>
  Title<br>
  <%= f.text_field(:title, {:class => 'form-control'}) %>
</p>
<p>
  Body<br>
  <%= f.text_area(:body, {:class => 'form-control'}) %>
</p>
<p>
  Price<br>
  <%= f.text_field(:price, {:class => 'form-control'}) %>
</p>
<p>
  <%= f.submit({:class => 'btn btn-success'}) %>
</p>
<% end %>

app/views/posts/show.html.erb
<h1> <%= @post.title %></h1>
<p> <%= @post.body %></p>
<p> <%= @post.price %></p>
<hr>
<% if @post.user == current_user %>
<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-warning' %>
<%= link_to "Delete", post_path(@post), method: :delete, data:{confirm: "R u sure u wanna delete it?"}, :class => 'btn btn-danger' %>
<% end %>