config/routes.rb
Rails.application.routes.draw do
  devise_for :users
root 'posts#index', as: 'home'

# get 'about' => 'pages#about', as: 'about'
get 'ingredients' => 'ingredients#index', as:'ingredients'
resources :posts, :ingredients, :items, :creators, :myclients, :myorders, :deliveries
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/creator.rb
class Creator < ApplicationRecord
  validates :name, :presence => {:message => "Заповніть назву виробника"}
  validates :registration_date, :presence => {:message => "Вкажіть дату реєстрації"}
  validates :city,  :presence => {:message => "Вкажіть місто виробника"}
  validates :specialization, :presence => {:message => "Для якої галузі створюються твори мистецтва цим виробником?"}
  validates :phone_number, :presence => {:message => "Заповніть номер телефону"}
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :myorder
  validates :price, :presence => {:message => "Вкажіть ціну доставки"}
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :title, presence: true, length: {minimum: 8}
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :creator
    validates :name, :presence => {:message => "Вкажіть назву творіння"}
    validates :price,  numericality: {greater_than: 0, :message => "Розкрийте вартість цього шедевру, ціна має бути більша за 0"}
    validates :production_date, :presence => {:message => "Коли було створене це диво?"}
    validates :storage_time, numericality: {greater_than: 0, :message => "Скільки місяців служитиме цей витвір?"}
end

app/models/myclient.rb
class Myclient < ApplicationRecord
  validates :name, :presence => {:message => "Вкажіть ім'я клієнта"}
  validates :birth,  :presence => {:message => "Заповніть дату народження"}
  validates :company, :presence => {:message => "У якій компанії працює Ваш замовник?"}
  validates :phone_number, :presence => {:message => "Вкажіть номер телефону"}
  validates :city, :presence => {:message => "Із якого міста замовник?"}
end

app/models/myorder.rb
class Myorder < ApplicationRecord
  belongs_to :myclient
  belongs_to :item

  validates :order_date,  :presence => {:message => "Заповніть дату замовлення"}
  validates :amount, numericality: {greater_than: 0, :message => "Скільки одиниць товару замовлено? (не менше однієї)"}

end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: {minimum: 8}
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
before_action :authenticate_user!, except: [:index, :show]
  def show
    @item = Items.find(params[:id])
  end

  def destroy
    @item = Item.find(params[:id])

    @item.destroy

    redirect_to Item
  end

  def new
    @item = Item.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if(@item.update(item_params))                  #save in the table when validated
    redirect_to Item
    else
    render 'edit' #if title not validated
  end
  end


    def create
      @item = Item.new(item_params)

      respond_to do |format|
         if @item.save
           format.html { redirect_to Item, notice: 'Success'}
         else
           format.html { render :new}
      end
    end

  end

  private def item_params
    params.require(:item).permit(:name, :price, :production_date, :storage_time, :creator_id ) #take allowed data
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
   @heading = "About"
   @text = "some text"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
# http_basic_authenticate_with name: "admin", password: "1",
# except: [:index, :show]
before_action :authenticate_user!, except: [:index, :show]

  def index
    @post = Post.all
  end

  def new
    # @post = Post.new
    @post = current_user.posts.build
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if(@post.update(post_params))                  #save in the table when validated
    redirect_to @post
    else
    render 'edit' #if title not validated
  end
  end

def destroy
  @post = Post.find(params[:id])
  @post.destroy
  redirect_to posts_path
end

  def create

    @post = current_user.posts.build(post_params) #write to the create_table

  respond_to do |format|
     if @post.save
       format.html { redirect_to @post, notice: 'Success'}
     else
       format.html { render :new}
  end
end
end

  private def post_params
    params.require(:post).permit(:title, :body, :price) #take allowed data
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creators_helper.rb
module CreatorsHelper
end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/myclient_helper.rb
module MyclientHelper
end

app/helpers/myorder_helper.rb
module MyorderHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Shu-r-shu" %></title>
    <%= csrf_meta_tags %>


    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= stylesheet_link_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" %>
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-bold">Shu-r-shu</h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <span class="p-2 text-dark"><%= link_to "Головна", home_path %></span>
        <span class="p-2 text-dark"><%= link_to "Товари", items_path %></span>
        <span class="p-2 text-dark"><%= link_to "Виробники", creators_path %></span>
        <span class="p-2 text-dark"><%= link_to "Замовники", myclients_path %></span>
        <span class="p-2 text-dark"><%= link_to "Замовлення", myorders_path %></span>
        <span class="p-2 text-dark"><%= link_to "Доставка", deliveries_path %></span>
      </nav>

       <% if !user_signed_in? %>
      <span class="p-2 text-dark"><%= link_to "Зареєструватися", new_user_registration_path %></span>
      <span class="p-2 text-dark"><%= link_to "Увійти в систему", new_user_session_path %></span>
       <% else %>
       <span class="p-2 text-dark"><%= link_to "Вийти", destroy_user_session_path, :method => :delete %></span>
       <span class="p-2 text-dark">Раді вітати, <%= current_user.email %></span>
       <% end %>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <!-- <%= bootstrap_flash %> -->
          <p class="notice"><%= notice %></p>
       <!-- <p class="alert"><%= alert %></p> -->
<!-- <span class="p-2 text-dark"><%= link_to "Add post", new_post_path %></span> -->

          <%= yield %>
        </div>
        <!-- <div class="col-lg-3">
          <div class="well sidebar-nav">

            <ul class="nav" style="display:contents;">

              <li><%= link_to "Головна", home_path %></li>
              <li><%= link_to "Товари", items_path %></li>
              <li><%= link_to "Виробники", creators_path %></li>
              <li><%= link_to "Замовники", myclients_path %></li>
              <li><%= link_to "Замовлення", myorders_path %></li>
              <li><%= link_to "Доставка", deliveries_path %></li>
            </ul>
          </div>
        </div> -->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2019</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/pages/about.html.erb
<h3> <%= @heading %> </h3>
<p> <%= @text %> </p>